### PR TITLE
Support indented definition references within code blocks.

### PR DESCRIPTION
**Pull request by ThomasSpurden**
Preserves indentation on output in all formats.

I am finding this is essential in C; e.g.
```
When foo is set some extra processing is done for reasons
   << handle foo case >>=
   do things

Main processing

   << * >>=
   << normal processing >>
   if(foo) {
       << handle foo case >>
   }
```

It's a long time since I have done any Haskell so hopefully this isn't too awful.

This is issue #7

### CODE REVIEW

**Comment by cdosborn** [comment]
Nice work. GIve me a day to look over some of these changes.

**Comment by cdosborn** [comment]
So I created a feature branch for this with the merges, can you contribute a test at the bottom https://github.com/cdosborn/lit/blob/indented-macro-refs/test/Tests.hs

**Comment by ThomasSpurden** [comment]
I've added a basic test for the indented macro expansion.
As an aside, is there an easy way to run the tests? I temporarily hacked the main function to run them, is there a better way?

**Comment by cdosborn** [comment]
Awesome, btw I added a readme in the tests dir for a quick command to run the tests.

**Pull request merged**
